from periodic_table.model import Category, Element

ELEMENTS: list[Element] = [
    # Period 1
    Element(atomic_number=1,   symbol="H",   name="Hydrogen",      mass=1.008,
            period=1, group=1,    category=Category.NONMETAL,
            electron_config="1s1",
            electronegativity=2.20, phase="gas"),
    Element(atomic_number=2,   symbol="He",  name="Helium",        mass=4.0026,
            period=1, group=18,   category=Category.NOBLE_GAS,
            electron_config="1s2",
            electronegativity=None, phase="gas"),

    # Period 2
    Element(atomic_number=3,   symbol="Li",  name="Lithium",       mass=6.94,
            period=2, group=1,    category=Category.ALKALI_METAL,
            electron_config="[He] 2s1",
            electronegativity=0.98, phase="solid"),
    Element(atomic_number=4,   symbol="Be",  name="Beryllium",     mass=9.0122,
            period=2, group=2,    category=Category.ALKALINE_EARTH,
            electron_config="[He] 2s2",
            electronegativity=1.57, phase="solid"),
    Element(atomic_number=5,   symbol="B",   name="Boron",         mass=10.81,
            period=2, group=13,   category=Category.METALLOID,
            electron_config="[He] 2s2 2p1",
            electronegativity=2.04, phase="solid"),
    Element(atomic_number=6,   symbol="C",   name="Carbon",        mass=12.011,
            period=2, group=14,   category=Category.NONMETAL,
            electron_config="[He] 2s2 2p2",
            electronegativity=2.55, phase="solid"),
    Element(atomic_number=7,   symbol="N",   name="Nitrogen",      mass=14.007,
            period=2, group=15,   category=Category.NONMETAL,
            electron_config="[He] 2s2 2p3",
            electronegativity=3.04, phase="gas"),
    Element(atomic_number=8,   symbol="O",   name="Oxygen",        mass=15.999,
            period=2, group=16,   category=Category.NONMETAL,
            electron_config="[He] 2s2 2p4",
            electronegativity=3.44, phase="gas"),
    Element(atomic_number=9,   symbol="F",   name="Fluorine",      mass=18.998,
            period=2, group=17,   category=Category.HALOGEN,
            electron_config="[He] 2s2 2p5",
            electronegativity=3.98, phase="gas"),
    Element(atomic_number=10,  symbol="Ne",  name="Neon",          mass=20.180,
            period=2, group=18,   category=Category.NOBLE_GAS,
            electron_config="[He] 2s2 2p6",
            electronegativity=None, phase="gas"),

    # Period 3
    Element(atomic_number=11,  symbol="Na",  name="Sodium",        mass=22.990,
            period=3, group=1,    category=Category.ALKALI_METAL,
            electron_config="[Ne] 3s1",
            electronegativity=0.93, phase="solid"),
    Element(atomic_number=12,  symbol="Mg",  name="Magnesium",     mass=24.305,
            period=3, group=2,    category=Category.ALKALINE_EARTH,
            electron_config="[Ne] 3s2",
            electronegativity=1.31, phase="solid"),
    Element(atomic_number=13,  symbol="Al",  name="Aluminium",     mass=26.982,
            period=3, group=13,   category=Category.POST_TRANSITION,
            electron_config="[Ne] 3s2 3p1",
            electronegativity=1.61, phase="solid"),
    Element(atomic_number=14,  symbol="Si",  name="Silicon",       mass=28.085,
            period=3, group=14,   category=Category.METALLOID,
            electron_config="[Ne] 3s2 3p2",
            electronegativity=1.90, phase="solid"),
    Element(atomic_number=15,  symbol="P",   name="Phosphorus",    mass=30.974,
            period=3, group=15,   category=Category.NONMETAL,
            electron_config="[Ne] 3s2 3p3",
            electronegativity=2.19, phase="solid"),
    Element(atomic_number=16,  symbol="S",   name="Sulfur",        mass=32.06,
            period=3, group=16,   category=Category.NONMETAL,
            electron_config="[Ne] 3s2 3p4",
            electronegativity=2.58, phase="solid"),
    Element(atomic_number=17,  symbol="Cl",  name="Chlorine",      mass=35.45,
            period=3, group=17,   category=Category.HALOGEN,
            electron_config="[Ne] 3s2 3p5",
            electronegativity=3.16, phase="gas"),
    Element(atomic_number=18,  symbol="Ar",  name="Argon",         mass=39.948,
            period=3, group=18,   category=Category.NOBLE_GAS,
            electron_config="[Ne] 3s2 3p6",
            electronegativity=None, phase="gas"),

    # Period 4
    Element(atomic_number=19,  symbol="K",   name="Potassium",     mass=39.098,
            period=4, group=1,    category=Category.ALKALI_METAL,
            electron_config="[Ar] 4s1",
            electronegativity=0.82, phase="solid"),
    Element(atomic_number=20,  symbol="Ca",  name="Calcium",       mass=40.078,
            period=4, group=2,    category=Category.ALKALINE_EARTH,
            electron_config="[Ar] 4s2",
            electronegativity=1.00, phase="solid"),
    Element(atomic_number=21,  symbol="Sc",  name="Scandium",      mass=44.956,
            period=4, group=3,    category=Category.TRANSITION_METAL,
            electron_config="[Ar] 3d1 4s2",
            electronegativity=1.36, phase="solid"),
    Element(atomic_number=22,  symbol="Ti",  name="Titanium",      mass=47.867,
            period=4, group=4,    category=Category.TRANSITION_METAL,
            electron_config="[Ar] 3d2 4s2",
            electronegativity=1.54, phase="solid"),
    Element(atomic_number=23,  symbol="V",   name="Vanadium",      mass=50.942,
            period=4, group=5,    category=Category.TRANSITION_METAL,
            electron_config="[Ar] 3d3 4s2",
            electronegativity=1.63, phase="solid"),
    Element(atomic_number=24,  symbol="Cr",  name="Chromium",      mass=51.996,
            period=4, group=6,    category=Category.TRANSITION_METAL,
            electron_config="[Ar] 3d5 4s1",
            electronegativity=1.66, phase="solid"),
    Element(atomic_number=25,  symbol="Mn",  name="Manganese",     mass=54.938,
            period=4, group=7,    category=Category.TRANSITION_METAL,
            electron_config="[Ar] 3d5 4s2",
            electronegativity=1.55, phase="solid"),
    Element(atomic_number=26,  symbol="Fe",  name="Iron",          mass=55.845,
            period=4, group=8,    category=Category.TRANSITION_METAL,
            electron_config="[Ar] 3d6 4s2",
            electronegativity=1.83, phase="solid"),
    Element(atomic_number=27,  symbol="Co",  name="Cobalt",        mass=58.933,
            period=4, group=9,    category=Category.TRANSITION_METAL,
            electron_config="[Ar] 3d7 4s2",
            electronegativity=1.88, phase="solid"),
    Element(atomic_number=28,  symbol="Ni",  name="Nickel",        mass=58.693,
            period=4, group=10,   category=Category.TRANSITION_METAL,
            electron_config="[Ar] 3d8 4s2",
            electronegativity=1.91, phase="solid"),
    Element(atomic_number=29,  symbol="Cu",  name="Copper",        mass=63.546,
            period=4, group=11,   category=Category.TRANSITION_METAL,
            electron_config="[Ar] 3d10 4s1",
            electronegativity=1.90, phase="solid"),
    Element(atomic_number=30,  symbol="Zn",  name="Zinc",          mass=65.38,
            period=4, group=12,   category=Category.TRANSITION_METAL,
            electron_config="[Ar] 3d10 4s2",
            electronegativity=1.65, phase="solid"),
    Element(atomic_number=31,  symbol="Ga",  name="Gallium",       mass=69.723,
            period=4, group=13,   category=Category.POST_TRANSITION,
            electron_config="[Ar] 3d10 4s2 4p1",
            electronegativity=1.81, phase="solid"),
    Element(atomic_number=32,  symbol="Ge",  name="Germanium",     mass=72.630,
            period=4, group=14,   category=Category.METALLOID,
            electron_config="[Ar] 3d10 4s2 4p2",
            electronegativity=2.01, phase="solid"),
    Element(atomic_number=33,  symbol="As",  name="Arsenic",       mass=74.922,
            period=4, group=15,   category=Category.METALLOID,
            electron_config="[Ar] 3d10 4s2 4p3",
            electronegativity=2.18, phase="solid"),
    Element(atomic_number=34,  symbol="Se",  name="Selenium",      mass=78.971,
            period=4, group=16,   category=Category.NONMETAL,
            electron_config="[Ar] 3d10 4s2 4p4",
            electronegativity=2.55, phase="solid"),
    Element(atomic_number=35,  symbol="Br",  name="Bromine",       mass=79.904,
            period=4, group=17,   category=Category.HALOGEN,
            electron_config="[Ar] 3d10 4s2 4p5",
            electronegativity=2.96, phase="liquid"),
    Element(atomic_number=36,  symbol="Kr",  name="Krypton",       mass=83.798,
            period=4, group=18,   category=Category.NOBLE_GAS,
            electron_config="[Ar] 3d10 4s2 4p6",
            electronegativity=None, phase="gas"),

    # Period 5
    Element(atomic_number=37,  symbol="Rb",  name="Rubidium",      mass=85.468,
            period=5, group=1,    category=Category.ALKALI_METAL,
            electron_config="[Kr] 5s1",
            electronegativity=0.82, phase="solid"),
    Element(atomic_number=38,  symbol="Sr",  name="Strontium",     mass=87.62,
            period=5, group=2,    category=Category.ALKALINE_EARTH,
            electron_config="[Kr] 5s2",
            electronegativity=0.95, phase="solid"),
    Element(atomic_number=39,  symbol="Y",   name="Yttrium",       mass=88.906,
            period=5, group=3,    category=Category.TRANSITION_METAL,
            electron_config="[Kr] 4d1 5s2",
            electronegativity=1.22, phase="solid"),
    Element(atomic_number=40,  symbol="Zr",  name="Zirconium",     mass=91.224,
            period=5, group=4,    category=Category.TRANSITION_METAL,
            electron_config="[Kr] 4d2 5s2",
            electronegativity=1.33, phase="solid"),
    Element(atomic_number=41,  symbol="Nb",  name="Niobium",       mass=92.906,
            period=5, group=5,    category=Category.TRANSITION_METAL,
            electron_config="[Kr] 4d4 5s1",
            electronegativity=1.60, phase="solid"),
    Element(atomic_number=42,  symbol="Mo",  name="Molybdenum",    mass=95.95,
            period=5, group=6,    category=Category.TRANSITION_METAL,
            electron_config="[Kr] 4d5 5s1",
            electronegativity=2.16, phase="solid"),
    Element(atomic_number=43,  symbol="Tc",  name="Technetium",    mass=97.0,
            period=5, group=7,    category=Category.TRANSITION_METAL,
            electron_config="[Kr] 4d5 5s2",
            electronegativity=1.90, phase="solid"),
    Element(atomic_number=44,  symbol="Ru",  name="Ruthenium",     mass=101.07,
            period=5, group=8,    category=Category.TRANSITION_METAL,
            electron_config="[Kr] 4d7 5s1",
            electronegativity=2.20, phase="solid"),
    Element(atomic_number=45,  symbol="Rh",  name="Rhodium",       mass=102.91,
            period=5, group=9,    category=Category.TRANSITION_METAL,
            electron_config="[Kr] 4d8 5s1",
            electronegativity=2.28, phase="solid"),
    Element(atomic_number=46,  symbol="Pd",  name="Palladium",     mass=106.42,
            period=5, group=10,   category=Category.TRANSITION_METAL,
            electron_config="[Kr] 4d10",
            electronegativity=2.20, phase="solid"),
    Element(atomic_number=47,  symbol="Ag",  name="Silver",        mass=107.87,
            period=5, group=11,   category=Category.TRANSITION_METAL,
            electron_config="[Kr] 4d10 5s1",
            electronegativity=1.93, phase="solid"),
    Element(atomic_number=48,  symbol="Cd",  name="Cadmium",       mass=112.41,
            period=5, group=12,   category=Category.TRANSITION_METAL,
            electron_config="[Kr] 4d10 5s2",
            electronegativity=1.69, phase="solid"),
    Element(atomic_number=49,  symbol="In",  name="Indium",        mass=114.82,
            period=5, group=13,   category=Category.POST_TRANSITION,
            electron_config="[Kr] 4d10 5s2 5p1",
            electronegativity=1.78, phase="solid"),
    Element(atomic_number=50,  symbol="Sn",  name="Tin",           mass=118.71,
            period=5, group=14,   category=Category.POST_TRANSITION,
            electron_config="[Kr] 4d10 5s2 5p2",
            electronegativity=1.96, phase="solid"),
    Element(atomic_number=51,  symbol="Sb",  name="Antimony",      mass=121.76,
            period=5, group=15,   category=Category.METALLOID,
            electron_config="[Kr] 4d10 5s2 5p3",
            electronegativity=2.05, phase="solid"),
    Element(atomic_number=52,  symbol="Te",  name="Tellurium",     mass=127.60,
            period=5, group=16,   category=Category.METALLOID,
            electron_config="[Kr] 4d10 5s2 5p4",
            electronegativity=2.10, phase="solid"),
    Element(atomic_number=53,  symbol="I",   name="Iodine",        mass=126.90,
            period=5, group=17,   category=Category.HALOGEN,
            electron_config="[Kr] 4d10 5s2 5p5",
            electronegativity=2.66, phase="solid"),
    Element(atomic_number=54,  symbol="Xe",  name="Xenon",         mass=131.29,
            period=5, group=18,   category=Category.NOBLE_GAS,
            electron_config="[Kr] 4d10 5s2 5p6",
            electronegativity=None, phase="gas"),

    # Period 6
    Element(atomic_number=55,  symbol="Cs",  name="Caesium",       mass=132.91,
            period=6, group=1,    category=Category.ALKALI_METAL,
            electron_config="[Xe] 6s1",
            electronegativity=0.79, phase="solid"),
    Element(atomic_number=56,  symbol="Ba",  name="Barium",        mass=137.33,
            period=6, group=2,    category=Category.ALKALINE_EARTH,
            electron_config="[Xe] 6s2",
            electronegativity=0.89, phase="solid"),

    # Lanthanides Z=57..71 (period=6, group=None)
    Element(atomic_number=57,  symbol="La",  name="Lanthanum",     mass=138.91,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 5d1 6s2",
            electronegativity=1.10, phase="solid"),
    Element(atomic_number=58,  symbol="Ce",  name="Cerium",        mass=140.12,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f1 5d1 6s2",
            electronegativity=1.12, phase="solid"),
    Element(atomic_number=59,  symbol="Pr",  name="Praseodymium",  mass=140.91,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f3 6s2",
            electronegativity=1.13, phase="solid"),
    Element(atomic_number=60,  symbol="Nd",  name="Neodymium",     mass=144.24,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f4 6s2",
            electronegativity=1.14, phase="solid"),
    Element(atomic_number=61,  symbol="Pm",  name="Promethium",    mass=145.0,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f5 6s2",
            electronegativity=1.13, phase="solid"),
    Element(atomic_number=62,  symbol="Sm",  name="Samarium",      mass=150.36,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f6 6s2",
            electronegativity=1.17, phase="solid"),
    Element(atomic_number=63,  symbol="Eu",  name="Europium",      mass=151.96,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f7 6s2",
            electronegativity=1.20, phase="solid"),
    Element(atomic_number=64,  symbol="Gd",  name="Gadolinium",    mass=157.25,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f7 5d1 6s2",
            electronegativity=1.20, phase="solid"),
    Element(atomic_number=65,  symbol="Tb",  name="Terbium",       mass=158.93,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f9 6s2",
            electronegativity=1.10, phase="solid"),
    Element(atomic_number=66,  symbol="Dy",  name="Dysprosium",    mass=162.50,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f10 6s2",
            electronegativity=1.22, phase="solid"),
    Element(atomic_number=67,  symbol="Ho",  name="Holmium",       mass=164.93,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f11 6s2",
            electronegativity=1.23, phase="solid"),
    Element(atomic_number=68,  symbol="Er",  name="Erbium",        mass=167.26,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f12 6s2",
            electronegativity=1.24, phase="solid"),
    Element(atomic_number=69,  symbol="Tm",  name="Thulium",       mass=168.93,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f13 6s2",
            electronegativity=1.25, phase="solid"),
    Element(atomic_number=70,  symbol="Yb",  name="Ytterbium",     mass=173.04,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f14 6s2",
            electronegativity=1.10, phase="solid"),
    Element(atomic_number=71,  symbol="Lu",  name="Lutetium",      mass=174.97,
            period=6, group=None, category=Category.LANTHANIDE,
            electron_config="[Xe] 4f14 5d1 6s2",
            electronegativity=1.27, phase="solid"),

    # Period 6 continued (post-lanthanide)
    Element(atomic_number=72,  symbol="Hf",  name="Hafnium",       mass=178.49,
            period=6, group=4,    category=Category.TRANSITION_METAL,
            electron_config="[Xe] 4f14 5d2 6s2",
            electronegativity=1.30, phase="solid"),
    Element(atomic_number=73,  symbol="Ta",  name="Tantalum",      mass=180.95,
            period=6, group=5,    category=Category.TRANSITION_METAL,
            electron_config="[Xe] 4f14 5d3 6s2",
            electronegativity=1.50, phase="solid"),
    Element(atomic_number=74,  symbol="W",   name="Tungsten",      mass=183.84,
            period=6, group=6,    category=Category.TRANSITION_METAL,
            electron_config="[Xe] 4f14 5d4 6s2",
            electronegativity=2.36, phase="solid"),
    Element(atomic_number=75,  symbol="Re",  name="Rhenium",       mass=186.21,
            period=6, group=7,    category=Category.TRANSITION_METAL,
            electron_config="[Xe] 4f14 5d5 6s2",
            electronegativity=1.90, phase="solid"),
    Element(atomic_number=76,  symbol="Os",  name="Osmium",        mass=190.23,
            period=6, group=8,    category=Category.TRANSITION_METAL,
            electron_config="[Xe] 4f14 5d6 6s2",
            electronegativity=2.20, phase="solid"),
    Element(atomic_number=77,  symbol="Ir",  name="Iridium",       mass=192.22,
            period=6, group=9,    category=Category.TRANSITION_METAL,
            electron_config="[Xe] 4f14 5d7 6s2",
            electronegativity=2.20, phase="solid"),
    Element(atomic_number=78,  symbol="Pt",  name="Platinum",      mass=195.08,
            period=6, group=10,   category=Category.TRANSITION_METAL,
            electron_config="[Xe] 4f14 5d9 6s1",
            electronegativity=2.28, phase="solid"),
    Element(atomic_number=79,  symbol="Au",  name="Gold",          mass=196.97,
            period=6, group=11,   category=Category.TRANSITION_METAL,
            electron_config="[Xe] 4f14 5d10 6s1",
            electronegativity=2.54, phase="solid"),
    Element(atomic_number=80,  symbol="Hg",  name="Mercury",       mass=200.59,
            period=6, group=12,   category=Category.TRANSITION_METAL,
            electron_config="[Xe] 4f14 5d10 6s2",
            electronegativity=2.00, phase="liquid"),
    Element(atomic_number=81,  symbol="Tl",  name="Thallium",      mass=204.38,
            period=6, group=13,   category=Category.POST_TRANSITION,
            electron_config="[Xe] 4f14 5d10 6s2 6p1",
            electronegativity=1.62, phase="solid"),
    Element(atomic_number=82,  symbol="Pb",  name="Lead",          mass=207.2,
            period=6, group=14,   category=Category.POST_TRANSITION,
            electron_config="[Xe] 4f14 5d10 6s2 6p2",
            electronegativity=2.33, phase="solid"),
    Element(atomic_number=83,  symbol="Bi",  name="Bismuth",       mass=208.98,
            period=6, group=15,   category=Category.POST_TRANSITION,
            electron_config="[Xe] 4f14 5d10 6s2 6p3",
            electronegativity=2.02, phase="solid"),
    Element(atomic_number=84,  symbol="Po",  name="Polonium",      mass=209.0,
            period=6, group=16,   category=Category.POST_TRANSITION,
            electron_config="[Xe] 4f14 5d10 6s2 6p4",
            electronegativity=2.00, phase="solid"),
    Element(atomic_number=85,  symbol="At",  name="Astatine",      mass=210.0,
            period=6, group=17,   category=Category.HALOGEN,
            electron_config="[Xe] 4f14 5d10 6s2 6p5",
            electronegativity=2.20, phase="solid"),
    Element(atomic_number=86,  symbol="Rn",  name="Radon",         mass=222.0,
            period=6, group=18,   category=Category.NOBLE_GAS,
            electron_config="[Xe] 4f14 5d10 6s2 6p6",
            electronegativity=None, phase="gas"),

    # Period 7
    Element(atomic_number=87,  symbol="Fr",  name="Francium",      mass=223.0,
            period=7, group=1,    category=Category.ALKALI_METAL,
            electron_config="[Rn] 7s1",
            electronegativity=0.70, phase="solid"),
    Element(atomic_number=88,  symbol="Ra",  name="Radium",        mass=226.0,
            period=7, group=2,    category=Category.ALKALINE_EARTH,
            electron_config="[Rn] 7s2",
            electronegativity=0.89, phase="solid"),

    # Actinides Z=89..103 (period=7, group=None)
    Element(atomic_number=89,  symbol="Ac",  name="Actinium",      mass=227.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 6d1 7s2",
            electronegativity=1.10, phase="solid"),
    Element(atomic_number=90,  symbol="Th",  name="Thorium",       mass=232.04,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 6d2 7s2",
            electronegativity=1.30, phase="solid"),
    Element(atomic_number=91,  symbol="Pa",  name="Protactinium",  mass=231.04,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f2 6d1 7s2",
            electronegativity=1.50, phase="solid"),
    Element(atomic_number=92,  symbol="U",   name="Uranium",       mass=238.03,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f3 6d1 7s2",
            electronegativity=1.38, phase="solid"),
    Element(atomic_number=93,  symbol="Np",  name="Neptunium",     mass=237.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f4 6d1 7s2",
            electronegativity=1.36, phase="solid"),
    Element(atomic_number=94,  symbol="Pu",  name="Plutonium",     mass=244.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f6 7s2",
            electronegativity=1.28, phase="solid"),
    Element(atomic_number=95,  symbol="Am",  name="Americium",     mass=243.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f7 7s2",
            electronegativity=1.13, phase="solid"),
    Element(atomic_number=96,  symbol="Cm",  name="Curium",        mass=247.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f7 6d1 7s2",
            electronegativity=1.28, phase="solid"),
    Element(atomic_number=97,  symbol="Bk",  name="Berkelium",     mass=247.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f9 7s2",
            electronegativity=1.30, phase="solid"),
    Element(atomic_number=98,  symbol="Cf",  name="Californium",   mass=251.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f10 7s2",
            electronegativity=1.30, phase="solid"),
    Element(atomic_number=99,  symbol="Es",  name="Einsteinium",   mass=252.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f11 7s2",
            electronegativity=1.30, phase="solid"),
    Element(atomic_number=100, symbol="Fm",  name="Fermium",       mass=257.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f12 7s2",
            electronegativity=1.30, phase="solid"),
    Element(atomic_number=101, symbol="Md",  name="Mendelevium",   mass=258.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f13 7s2",
            electronegativity=1.30, phase="solid"),
    Element(atomic_number=102, symbol="No",  name="Nobelium",      mass=259.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f14 7s2",
            electronegativity=1.30, phase="solid"),
    Element(atomic_number=103, symbol="Lr",  name="Lawrencium",    mass=262.0,
            period=7, group=None, category=Category.ACTINIDE,
            electron_config="[Rn] 5f14 7s2 7p1",
            electronegativity=1.30, phase="solid"),

    # Period 7 continued — superheavies (Z=104..118, phase="unknown")
    Element(atomic_number=104, symbol="Rf",  name="Rutherfordium", mass=267.0,
            period=7, group=4,    category=Category.TRANSITION_METAL,
            electron_config="[Rn] 5f14 6d2 7s2",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=105, symbol="Db",  name="Dubnium",       mass=268.0,
            period=7, group=5,    category=Category.TRANSITION_METAL,
            electron_config="[Rn] 5f14 6d3 7s2",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=106, symbol="Sg",  name="Seaborgium",    mass=269.0,
            period=7, group=6,    category=Category.TRANSITION_METAL,
            electron_config="[Rn] 5f14 6d4 7s2",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=107, symbol="Bh",  name="Bohrium",       mass=270.0,
            period=7, group=7,    category=Category.TRANSITION_METAL,
            electron_config="[Rn] 5f14 6d5 7s2",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=108, symbol="Hs",  name="Hassium",       mass=269.0,
            period=7, group=8,    category=Category.TRANSITION_METAL,
            electron_config="[Rn] 5f14 6d6 7s2",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=109, symbol="Mt",  name="Meitnerium",    mass=278.0,
            period=7, group=9,    category=Category.TRANSITION_METAL,
            electron_config="[Rn] 5f14 6d7 7s2",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=110, symbol="Ds",  name="Darmstadtium",  mass=281.0,
            period=7, group=10,   category=Category.TRANSITION_METAL,
            electron_config="[Rn] 5f14 6d8 7s2",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=111, symbol="Rg",  name="Roentgenium",   mass=282.0,
            period=7, group=11,   category=Category.TRANSITION_METAL,
            electron_config="[Rn] 5f14 6d9 7s2",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=112, symbol="Cn",  name="Copernicium",   mass=285.0,
            period=7, group=12,   category=Category.TRANSITION_METAL,
            electron_config="[Rn] 5f14 6d10 7s2",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=113, symbol="Nh",  name="Nihonium",      mass=286.0,
            period=7, group=13,   category=Category.POST_TRANSITION,
            electron_config="[Rn] 5f14 6d10 7s2 7p1",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=114, symbol="Fl",  name="Flerovium",     mass=289.0,
            period=7, group=14,   category=Category.POST_TRANSITION,
            electron_config="[Rn] 5f14 6d10 7s2 7p2",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=115, symbol="Mc",  name="Moscovium",     mass=290.0,
            period=7, group=15,   category=Category.POST_TRANSITION,
            electron_config="[Rn] 5f14 6d10 7s2 7p3",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=116, symbol="Lv",  name="Livermorium",   mass=293.0,
            period=7, group=16,   category=Category.POST_TRANSITION,
            electron_config="[Rn] 5f14 6d10 7s2 7p4",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=117, symbol="Ts",  name="Tennessine",    mass=294.0,
            period=7, group=17,   category=Category.HALOGEN,
            electron_config="[Rn] 5f14 6d10 7s2 7p5",
            electronegativity=None, phase="unknown"),
    Element(atomic_number=118, symbol="Og",  name="Oganesson",     mass=294.0,
            period=7, group=18,   category=Category.NOBLE_GAS,
            electron_config="[Rn] 5f14 6d10 7s2 7p6",
            electronegativity=None, phase="unknown"),
]
